symfony_data:
    image: debian:jessie
    volumes:
        - ../api:/var/www/api
node_data:
    image: debian:jessie
    volumes:
        - ../public:/var/www/public
api:
    build: ./php
    volumes_from:
        - symfony_data
node:
    build: ./node
    volumes_from:
        - node_data
nginx:
    image: nginx
    ports:
        - "8080:80"
    links:
        - api:api
        - node:node
    volumes_from:
        - symfony_data
        - node_data
    volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/logs:/var/log/nginx/
postgres_data:
    image: debian:jessie
    volumes:
        - /var/lib/postgresql
postgres:
    image: postgres
    ports:
        - "5432:5432"
    volumes_from:
        - postgres_data
    environment:
        - POSTGRES_USER=sania
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=symfony
